services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hireflow
      POSTGRES_USER: hireflow
      POSTGRES_PASSWORD: hireflow_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
